extract reward tokens by reward program admin
cardstack/card-pay-protocol pull request #139
Opened 2021-11-10 17:27 UTC by tintinthong

- extracts to any safe

2021-11-10 20:01 UTC, alex-cardstack requested changes

2021-11-10 20:01 UTC, alex-cardstack commented on contracts/RewardPool.sol
> +    rewardBalance[rewardProgramID][token] = rewardBalance[rewardProgramID][
Maybe it's checked earlier but should balance be checked here?

```suggestion
    require(rewardBalance[rewardProgramID][token] >= amount, "Not enough tokens to withdraw")
    rewardBalance[rewardProgramID][token] = rewardBalance[rewardProgramID][
```

2021-11-10 20:01 UTC, alex-cardstack commented on test/RewardPool-test.js
> +    describe.only("extractRewardTokens", function () {
```suggestion
    describe("extractRewardTokens", function () {
```

2021-11-10 20:01 UTC, alex-cardstack commented on test/RewardPool-test.js
> +    });
Maybe worth adding some unhappy path cases like trying to withdraw without enough balance maybe

2021-11-12 03:58 UTC, tintinthong commented
Im going to rename everything to `recoverRewardTokens` rather than `extract`. Extract just sounds wrong and unnecessarily surgical.

2021-11-12 07:59 UTC, tintinthong commented
So @alex-cardstack I made a fix. I would appreciate your input on `setupProtocol` function. Currently it is only used in the reward pool test. But I created it witth the intention of making a god fixture-making function as a `before` in each test file. 

For example, reward pool the structure wud be like this 

- `before() setupProtocol` 
- `describe` > `beforeEach` > `RewardPool.new() & RewardPool.setup()` 

The implementation of `setupProtocol` is incomplete, but I wonder if it makes sense to actually do this in every contract test file and just destructure out the things that you need for your test. It would be a great to have if this `setupProtocol` function was intelligent enough to setup only the required dependecy thru some resolution logic. For example, if I require rewardPool, then rewardManger, tokenManager, versionManager, tally address are all setup for me. Wonder if there's a library to handle such a thing. 

hassan ahd the idea of making fixtures for different protocol classes -- like prepaid card & revenue (payment) / rewards.

2021-11-12 20:21 UTC, alex-cardstack commented
> So @alex-cardstack I made a fix in the test paying reward pool with a prepaid card this was screwed up by the setupProtocol. I would appreciate your input on setupProtocol function. Currently it is only used in the reward pool test. But I created it witth the intention of making a god fixture-making function as a before in each test file.

> For example, reward pool the structure wud be like this

> before() setupProtocol
> describe > beforeEach > RewardPool.new() & RewardPool.setup()

This makes sense. I did have some issues with the before being run before all tests not beforeEach - I worked around it, it wasn't terrible.

I do like the idea of it being easy to have the whole ecosystem set up easily for every test. It makes it much easier to test things.

> The implementation of setupProtocol is incomplete, but I wonder if it makes sense to actually do this in every contract test file and just destructure out the things that you need for your test. It would be a great to have if this setupProtocol function was intelligent enough to setup only the required dependecy thru some resolution logic. For example, if I require rewardPool, then rewardManger, tokenManager, versionManager, tally address are all setup for me. Wonder if there's a library to handle such a thing.

I can't think of one off the top of my head, maybe we can just do it with lazy accessors.

So we could have e.g. this API:

```js
import { getRewardManagerInstance } from "../setup";
let rewardManager = await getRewardManagerInstance()
```
And then implement it with:
```js
const rewardManagerInstance, paymentManagerInstance;

export async function getRewardManagerInstance() {
  if (rewardManagerInstance) { return rewardManagerInstance; }
  ...
  let paymentManagerInstance = await getPaymentManagerInstance();
  rewardManagerInstance = deploy(...);
  await rewardManagerInstance.setup(await getPaymentManagerInstance())
}

export function getPaymentManagerInstance() {
  if (paymentManagerInstance) { return paymentManagerInstance; }
  ...

}
```

This pattern would be composable - caching the deployed contracts so that they could be used individually. Essentially you get dependency ordering "for free" by just using the function calls and memoizing the results.

> hassan ahd the idea of making fixtures for different protocol classes -- like prepaid card & revenue (payment) / rewards.

However we setup the tests, I think it's basically a tradeoff of test running speed vs fidelity vs ease of maintenance and I'm not sure what's best at the moment.

Maybe just setting up the whole protocol at the beginning is the simplest way to make it realistic, I'm not sure

2021-11-12 21:02 UTC, alex-cardstack commented on contracts/RewardPool.sol
> +  function _getEOAOwner(address safe) internal returns (address) {
Yeah I think this definitely is not guaranteed to be right, I agree that the refactor will solve

2021-11-12 21:02 UTC, alex-cardstack approved these changes

2021-11-12 21:37 UTC, merged